"""Maintainer browser checks; requires Python Playwright and a Chromium executable.
Run in a disposable development environment, never required for site visitors.
"""
import json
import os
from pathlib import Path
import re
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(os.environ.get('TEST_OUTPUT', str(ROOT / 'test-output')))
OUT.mkdir(parents=True, exist_ok=True)
# Chromium navigation is restricted in this execution environment. Test our
# own source files in memory; do not change browser policies or fetch any site.
base = 'about:blank'
seed=(ROOT/'data/knowledge.mjs').read_text().replace('export ', '')
core=(ROOT/'assets/core.mjs').read_text().replace('export ', '')
app=re.sub(r'^import .*?;\n', '', (ROOT/'assets/app.mjs').read_text(), flags=re.M)
app=app.replace('import.meta.url', json.dumps('https://fixture.invalid/Knowledge-Graph-Demo/assets/app.mjs?v=0.2'))
html=(ROOT/'index.html').read_text()
html=re.sub(r'<script type="module".*?</script>', '', html)
html=re.sub(r'<link rel="stylesheet".*?>', lambda m: '<style>'+ (ROOT/'assets/app.css').read_text()+'</style>', html)
atlas=json.loads((ROOT/'data/atlas.json').read_text())
bootstrap='async () => {'+seed+'\n'+core+'\n'+app+'\n}'
def route(fragment):
    page.evaluate('(hash) => { location.hash=hash; }', fragment)
    page.wait_for_timeout(60)
def load_fixture(target):
    target.set_content(html)
    target.evaluate("(data)=>{ window.fetch = async(url)=>{if(String(url)!=='https://fixture.invalid/Knowledge-Graph-Demo/data/atlas.json?v=0.2') throw Error('Unexpected fixture request'); return new Response(JSON.stringify(data), {status:200,headers:{'Content-Type':'application/json'}});};}", atlas)
    target.evaluate(bootstrap)
checks=[]
def passed(name):
    checks.append(name)
    print('PASS', name)

try:
  with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1100},device_scale_factor=1)
    page=context.new_page(); errors=[]; external=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:external.append(r.url) if not r.url.startswith(base.split(ROOT.name)[0]) else None)
    load_fixture(page)
    expect(page.locator('.realm')).to_have_count(8)
    expect(page.locator('.journey')).to_have_count(3)
    expect(page.locator('h1')).to_contain_text('big picture')
    passed('eight region cards and three guided journeys render from the real files')
    page.screenshot(path=str(OUT/'atlas-desktop.png'),full_page=True)
    page.locator('.realm[href="#topic/life"]').click()
    expect(page.locator('.empty-state h2')).to_have_text('Not yet populated')
    expect(page.locator('#graph')).to_have_count(0)
    passed('empty region clearly reports absent coverage')
    route('#atlas')
    page.locator('.realm[href="#topic/nature"]').click()
    page.locator('.topiccard[href="#topic/physics"]').click()
    page.locator('.topiccard[href="#map/gravitation"]').click()
    expect(page.locator('.crumbs')).to_contain_text('Nature')
    expect(page.locator('.crumbs')).to_contain_text('Physics')
    expect(page.locator('#graph .gnode')).to_have_count(11)
    passed('Nature / Physics / Gravitation drilldown reaches the seed graph')
    page.locator('[data-node="G08"]').click()
    expect(page.locator('#inspector h2')).to_have_text('General relativity')
    page.locator('#inspector a[href="#map/gravitation?statement=S06"]').click()
    expect(page.locator('#inspector')).to_contain_text('How do we know?')
    expect(page.locator('#inspector')).to_contain_text('Not passage-verified')
    expect(page.locator('#inspector')).to_contain_text('No assessment history or assessment timestamp')
    assert '2026-09-01' not in page.locator('#inspector').inner_text()
    passed('statement inspection separates a source field from verified support and invents no dates')
    page.screenshot(path=str(OUT/'gravity-desktop.png'),full_page=True)
    page.locator('.crumbs a[href="#topic/physics"]').click()
    expect(page.locator('h1')).to_have_text('Physics')
    page.go_back()
    expect(page.locator('#inspector')).to_contain_text('How do we know?')
    passed('breadcrumbs and browser back restore context')
    route('#atlas')
    page.locator('.realm[href="#topic/culture"]').click()
    page.locator('.topiccard[href="#topic/music"]').click()
    page.locator('.topiccard[href="#map/jazz"]').click()
    expect(page.locator('#inspector h2')).to_have_text('Jazz')
    passed('Culture / Music / Jazz route works')
    route('#map/jazz?statement=J07S')
    expect(page.locator('#inspector')).to_contain_text('Scripted illustration')
    expect(page.locator('.history li')).to_have_count(2)
    expect(page.locator('.history')).to_contain_text('plausible')
    expect(page.locator('.history')).to_contain_text('disputed')
    assert '2026-01-15' not in page.locator('#inspector').inner_text()
    page.locator('#inspector details summary').click()
    expect(page.locator('#inspector pre')).to_contain_text('2026-01-15')
    passed('correction is illustrative and original synthetic dates remain only in labelled details')
    route('#atlas')
    page.locator('.realm[href="#topic/mind"]').click()
    page.locator('.topiccard[href="#topic/emotions"]').click()
    page.locator('.topiccard[href="#map/love"]').click()
    expect(page.locator('.stable-id')).to_have_text('L01')
    passed('Mind / Emotions & relationships / Love route works')
    page.locator('.focus-route[href="#map/love-literature?node=L01"]').click()
    expect(page.locator('.stable-id')).to_have_text('L01')
    expect(page.locator('#graph .gnode')).to_have_count(3)
    expect(page.locator('.crumbs')).to_contain_text('Literature')
    page.locator('.focus-route[href="#map/love-practice?node=L01"]').click()
    expect(page.locator('.stable-id')).to_have_text('L01')
    expect(page.locator('#graph .gnode')).to_have_count(2)
    expect(page.locator('.crumbs')).to_contain_text('Ethics')
    passed('three perspectives keep Love identity L01 with distinct filtered views')
    page.close()
    page=context.new_page()
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:external.append(r.url))
    route('#map/love-practice?node=L01')
    load_fixture(page)
    expect(page.locator('.stable-id')).to_have_text('L01')
    expect(page.locator('#graph .gnode')).to_have_count(2)
    passed('direct deep link restores Love identity in a fresh document')
    route('#map/all')
    page.locator('#path-from').select_option('G01')
    page.locator('#path-to').select_option('L01')
    page.locator('#path-form button[type=submit]').click()
    expect(page.locator('#path-results h3')).to_contain_text('5 steps')
    expect(page.locator('#path-results')).to_contain_text('traversed backwards')
    expect(page.locator('#path-results')).to_contain_text('not a causal explanation')
    expect(page.locator('#graph .edge.path')).to_have_count(5)
    passed('mixed-direction path labels reversal and does not present it as causation')
    page.locator('#path-mode').select_option('directed')
    page.locator('#path-form button[type=submit]').click()
    expect(page.locator('#path-results')).to_contain_text('No path')
    passed('directed mode refuses the reversed path')
    page.locator('#statement-q').fill('Newton gravity')
    page.locator('#statement-search button').click()
    assert page.locator('#statement-results .statement').count()>0
    expect(page.locator('#statement-results')).to_contain_text('support unverified')
    page.locator('#statement-q').fill('zzzzzzzzzz')
    page.locator('#statement-search button').click()
    expect(page.locator('#statement-results')).to_contain_text('No matching statements')
    passed('statement retrieval and no-result state work without generation')
    page.locator('[data-node="G02"]').focus()
    page.keyboard.press('Enter')
    expect(page.locator('.stable-id')).to_have_text('G02')
    expect(page.locator('#inspector')).to_contain_text('No statements connect')
    passed('keyboard node navigation works and disconnected records remain honest')
    route('#atlas')
    page.locator('#global-q').fill('Love')
    page.locator('#global-search button').click()
    expect(page.locator('h1')).to_have_text('Find a concept')
    assert page.locator('.topiccard').count()>0
    passed('cross-collection concept search works')
    route('#map/%3Cscript%3E')
    expect(page.locator('h1')).to_contain_text('not in the atlas')
    passed('unknown routes fail safely')
    page.set_viewport_size({'width':390,'height':844})
    route('#atlas')
    expect(page.locator('.realm')).to_have_count(8)
    page.screenshot(path=str(OUT/'mobile-debug.png'),full_page=True)
    overflow=page.evaluate("[...document.querySelectorAll('body *')].map(e=>({tag:e.tagName,cls:e.className,x:e.getBoundingClientRect().x,w:e.getBoundingClientRect().width})).filter(e=>e.x+e.w>innerWidth+1)")
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), overflow
    page.screenshot(path=str(OUT/'atlas-mobile.png'),full_page=True)
    page.locator('.realm[href="#topic/nature"]').click()
    page.locator('.topiccard[href="#topic/physics"]').click()
    page.locator('.topiccard[href="#map/gravitation"]').click()
    expect(page.locator('#graph .gnode')).to_have_count(11)
    page.screenshot(path=str(OUT/'mobile-debug.png'),full_page=True)
    overflow=page.evaluate("[...document.querySelectorAll('body *')].map(e=>({tag:e.tagName,cls:e.className,x:e.getBoundingClientRect().x,w:e.getBoundingClientRect().width})).filter(e=>e.x+e.w>innerWidth+1)")
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), overflow
    page.screenshot(path=str(OUT/'graph-mobile.png'),full_page=True)
    passed('mobile atlas and graph routes work without horizontal overflow')
    assert not external,external
    assert not errors,errors
    passed('no external runtime requests or browser JavaScript errors')
    browser.close()
finally:
  pass
(OUT/'browser-results.json').write_text(json.dumps({'checks':checks,'passed':len(checks),'mode':'in-memory Chromium fixture; not live-network verification'},indent=2))
print(f'{len(checks)} browser scenarios passed')
