import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {nodes,statements,audit} from '../data/knowledge.mjs';
import {validate,ancestry,mappingFor,members,project,memberships,findPath,searchStatements,historyFor} from '../assets/core.mjs';
const atlas=JSON.parse(readFileSync(new URL('../data/atlas.json',import.meta.url)));
const all=project(nodes.map(n=>n.id),nodes,statements);
const snapshot=JSON.stringify({nodes,statements});
test('original 33 node IDs and 28 statement IDs retained',()=>{assert.equal(nodes.length,33);assert.equal(statements.length,28);for(const d of ['G','J','L'])for(let i=1;i<=11;i++)assert.ok(nodes.some(n=>n.id===d+String(i).padStart(2,'0')));});
test('references, unique IDs, atlas parents and memberships validate',()=>assert.equal(validate(nodes,statements,atlas),true));
test('eight regions and three primary journeys',()=>{assert.equal(atlas.realms.length,8);assert.equal(atlas.journeys.length,3);});
test('three complete drilldown paths',()=>{assert.deepEqual(ancestry('gravitation',atlas).map(t=>t.id),['nature','physics','gravitation']);assert.deepEqual(ancestry('jazz',atlas).map(t=>t.id),['culture','music','jazz']);assert.deepEqual(ancestry('love',atlas).map(t=>t.id),['mind','emotions','love']);});
test('Love is the same node through psychological, literary and ethical lenses',()=>{assert.deepEqual(memberships('L01',atlas).map(t=>t.id),['love','love-literature','love-practice']);for(const id of ['love','love-literature','love-practice'])assert.equal(mappingFor(id,atlas).focus,'L01');});
test('empty realms are genuinely unmapped',()=>{for(const id of ['life','society','technology','formal'])assert.deepEqual(members(id,atlas),[]);});
test('coverage counts deduplicate overlap within a region',()=>{assert.equal(members('culture',atlas).length,14);assert.equal(members('mind',atlas).length,11);assert.equal(members('values',atlas).length,2);});
test('projection never adds navigation edges or changes records',()=>{const view=project(members('culture',atlas),nodes,statements);for(const s of view.statements)assert.ok(statements.includes(s));assert.equal(JSON.stringify({nodes,statements}),snapshot);assert.equal(nodes.filter(n=>n.id==='L01').length,1);});
test('gravity to love is an explicit mixed-direction semantic path',()=>{const p=findPath(all,'G01','L01');assert.deepEqual(p.nodes,['G01','G11','L11','L10','L04','L01']);assert.deepEqual(p.steps.map(s=>s.reverse),[true,true,false,false,true]);});
test('directed traversal cannot silently reverse relations',()=>{assert.equal(findPath(all,'G01','L01',true),null);const p=findPath(all,'G03','G01',true);assert.deepEqual(p.nodes,['G03','G04','G05','G01']);});
test('same-node path is valid and empty',()=>assert.deepEqual(findPath(all,'L01','L01'),{nodes:['L01'],steps:[]}));
test('absent nodes and disconnected paths return null',()=>{assert.equal(findPath(all,'missing','L01'),null);assert.equal(findPath(all,'G02','L01'),null);assert.equal(findPath(all,'G01','J01'),null);});
test('search returns only existing statements and never generates a claim',()=>{const hits=searchStatements('Newton gravity',all);assert.ok(hits.length>0);assert.ok(hits.every(s=>statements.includes(s)));assert.deepEqual(searchStatements('zzzzzzz',all),[]);});
test('ordinary statements do not acquire artificial history',()=>{const h=historyFor(statements.find(s=>s.id==='S01'),audit);assert.deepEqual(h,{illustrative:false,entries:[]});});
test('original scripted correction values remain intact and labelled',()=>{const h=historyFor(statements.find(s=>s.id==='J07S'),audit);assert.equal(h.illustrative,true);assert.deepEqual(h.entries.map(e=>e.status),['plausible','disputed']);assert.deepEqual(h.entries.map(e=>e.date),['2026-01-15','2026-09-01']);assert.equal(h.entries[1].supersedes,'2026-01-15 assessment');});
test('audit does not claim passage-level verification',()=>assert.equal(audit.verification,'not_passage_verified'));
test('immutable records reject accidental writes',()=>{assert.throws(()=>{nodes[0].name='changed';},TypeError);assert.throws(()=>{statements[0].status='changed';},TypeError);});
test('unknown parents and cycles are rejected',()=>{const bad=structuredClone(atlas);bad.topics[0].parent='unknown';assert.throws(()=>validate(nodes,statements,bad));const cyc=structuredClone(atlas);cyc.topics[0].parent='gravitation';assert.throws(()=>validate(nodes,statements,cyc),/cycle/);});
test('duplicate and dangling statements are rejected',()=>{assert.throws(()=>validate(nodes,[...statements,statements[0]],atlas),/Duplicate/);assert.throws(()=>validate(nodes,[...statements,{id:'bad',s:'G01',o:'missing'}],atlas),/Dangling/);});
test('all operations preserve the seed snapshot',()=>assert.equal(JSON.stringify({nodes,statements}),snapshot));
