import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {nodes,statements,audit} from '../data/knowledge.mjs';
import {buildModel,safeURL} from '../assets/live-data-v03.mjs';
import {ancestry,members,memberships,project,findPath,historyFor,searchStatements} from '../assets/core.mjs';
const json=f=>JSON.parse(readFileSync(new URL('../data/'+f,import.meta.url)));
const inputs=()=>[json('atlas.json'),json('registry-v0.1.json'),json('democracy-batch-001.json'),json('release-v0.3.json')];
const make=(edit=()=>{})=>{const args=inputs();edit(...args);return buildModel(nodes,statements,...args);};
const m=make(),all=project(m.nodes.map(n=>n.id),m.nodes,m.statements);
for(const [file,sha] of [['knowledge.mjs','8d24280ff937f28e30fbbb0be8049caa74d02f2e'],['registry-v0.1.json','7ca5c07d4ed49724dac0a39072b73d1e7163c356'],['democracy-batch-001.json','8974e797f32f71da95cfda712800e379f287881b']])test('exact inspected Git blob: '+file,()=>{const b=readFileSync(new URL('../data/'+file,import.meta.url));assert.equal(createHash('sha1').update(`blob ${b.length}\0`).update(b).digest('hex'),sha);});
test('43 nodes and 34 statements; no additional inferred edges',()=>{assert.equal(m.nodes.length,43);assert.equal(m.statements.length,34);assert.equal(new Set(m.statements.map(s=>s.id)).size,34);});
test('all original object identities retained in projection',()=>{nodes.forEach(n=>assert.equal(m.nodes.find(x=>x.id===n.id),n));statements.forEach(s=>assert.equal(m.statements.find(x=>x.id===s.id),s));});
test('four journeys; only Society coverage extended',()=>{assert.equal(m.atlas.journeys.length,4);assert.equal(m.atlas.realms.length,8);assert.deepEqual(ancestry('democracy',m.atlas).map(x=>x.id),['society','government','democracy']);assert.equal(members('society',m.atlas).length,10);for(const r of ['life','technology','formal'])assert.deepEqual(members(r,m.atlas),[]);});
test('same Love identity across all prior lenses',()=>assert.deepEqual(memberships('L01',m.atlas).map(x=>x.id),['love','love-literature','love-practice']));
test('18 candidate mappings, 10 held, zero unmapped',()=>{const states=statements.map(s=>m.decisionFor(s).state);assert.equal(states.filter(x=>x==='candidate_binary').length,18);assert.equal(states.filter(x=>x==='held_for_roles').length,10);});
test('14 definitions and 7 deferred patterns',()=>{assert.equal(m.registry.relations.length,14);assert.equal(m.registry.patterns.length,7);});
test('six documentary statements retain all qualifiers and evidence chains',()=>{for(const s of m.statements.filter(s=>s.kind)){const e=m.evidenceFor(s.id);assert.deepEqual(s.qualifiers,e.record.content.qualifiers);assert.ok(e.attestations.length&&e.sources.length&&e.assessments.length);assert.equal(e.record.publication_allowed,false);}});
test('four sources, three UDHR passages are not three independent sources',()=>{assert.equal(m.batch.sources.length,4);assert.equal(m.batch.attestations.filter(a=>a.source_id==='DEM:S:UDHR').length,3);});
test('staging and assessment statuses preserved despite preview authorization',()=>{assert.equal(m.batch.state,'private_review_candidate');assert.equal(m.registry.policy.publication_allowed,false);assert.equal(m.release.authorization.verified_knowledge_publication,false);assert.ok(m.batch.assessments.every(a=>a.status==='AI_text_checked_pending_independent_review'));});
test('missing publication authorization fails closed',()=>assert.throws(()=>make((a,r,b,e)=>e.authorization.demo_display_authorized=false),/authorized/));
test('no automated promotion to verified knowledge',()=>assert.throws(()=>make((a,r,b,e)=>e.authorization.verified_knowledge_publication=true),/authorized/));
test('unallowlisted extra entry fails closed',()=>assert.throws(()=>make((a,r,b)=>b.statements.push({...b.statements[0],id:'EXTRA'})),/allowlist/));
test('duplicate definition aliases rejected',()=>assert.throws(()=>make((a,r)=>r.relations[1].aliases.push('authored')),/alias/));
test('new inference policy rejected',()=>assert.throws(()=>make((a,r)=>r.policy.inference_enabled=true),/Inference/));
test('dangling documentary endpoint rejected',()=>assert.throws(()=>make((a,r,b)=>b.statements[0].content.object='missing'),/endpoint/));
test('non-document endpoint rejected',()=>assert.throws(()=>make((a,r,b)=>b.nodes[0].type='Person'),/work/));
test('missing locator rejected',()=>assert.throws(()=>make((a,r,b)=>delete b.statements[0].content.qualifiers.locator),/scope/));
test('changed source edition rejected',()=>assert.throws(()=>make((a,r,b)=>b.sources[0].edition='Other edition'),/Edition/));
test('attestation from wrong work rejected',()=>assert.throws(()=>make((a,r,b)=>b.attestations[0].source_id='DEM:S:DECLARATION'),/Edition/));
test('cross-statement assessment basis rejected',()=>assert.throws(()=>make((a,r,b)=>b.assessments[0].basis=['DEM:AT:002']),/basis/));
test('promoted assessment rejected',()=>assert.throws(()=>make((a,r,b)=>b.assessments[0].status='established'),/promoted/));
test('real-world implementation cannot be inferred',()=>assert.throws(()=>make((a,r,b)=>b.assessments[0].world_implementation='effective'),/promoted/));
test('no silent population change',()=>assert.throws(()=>make((a,r,b)=>b.nodes[4].population='All residents in all eras'),/scope/));
test('mixed direction semantic path preserved; directed mode does not reverse',()=>{assert.deepEqual(findPath(all,'G01','L01').nodes,['G01','G11','L11','L10','L04','L01']);assert.equal(findPath(all,'G01','L01',true),null);});
test('new document path keeps Work to Proposition direction',()=>{assert.equal(findPath(all,'DEM:W:UDHR','DEM:P:PARTICIPATION',true).steps.length,1);assert.equal(findPath(all,'DEM:P:PARTICIPATION','DEM:W:UDHR',true),null);});
test('no invented bridge to other domains',()=>assert.equal(findPath(all,'G01','DEM:W:UDHR'),null));
test('history retained and no false new dates',()=>{assert.equal(historyFor(m.statements.find(s=>s.id==='J07S'),audit).illustrative,true);assert.deepEqual(historyFor(m.statements[0],audit).entries,[]);});
test('lexical sense qualifiers retained but roles not invented',()=>{const d=m.decisionFor(statements.find(s=>s.id==='X01'));assert.equal(d.pending.sense_kind,'physical');assert.ok(d.missing.includes('sense_node'));});
test('binary prediction missing scope is still identified',()=>assert.ok(m.decisionFor(statements.find(s=>s.id==='S07')).missing.includes('prediction_scope')));
test('source URLs require https without embedded credentials',()=>{for(const url of ['javascript:alert(1)','https://name:password@example.com','http://example.com','data:text/html,x'])assert.equal(safeURL(url),null);assert.equal(safeURL('https://example.com/a'),'https://example.com/a');});
test('unsafe URL rejected during batch loading',()=>assert.throws(()=>make((a,r,b)=>b.sources[0].url='javascript:bad()'),/URL/));
test('retrieval returns the attributed voting statement, not generated prose',()=>{const results=searchStatements('sex voting',all);assert.ok(results.some(s=>s.id==='DEM:ST:006'));assert.ok(results.every(s=>all.statements.includes(s)));});
test('source and registry input records are frozen after construction',()=>{assert.ok(Object.isFrozen(m.batch.statements[0].content.qualifiers));assert.throws(()=>m.registry.policy.inference_enabled=true,TypeError);});
